spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_cloud_2020

server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: payment8002 #只显示服务名，不显示主机信息
    prefer-ip-address: true #显示IP地址