server.port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment8001route        # 路由ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 提供服务的真实地址
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: payment8001route1       # 路由ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 提供服务的真实地址
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/openfeign/timeout

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-gatewat9527
    prefer-ip-address: true